server:
  port: 8080

spring:
  application:
    name: mcp-lab-server

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details=always

logging:
  level:
    root: INFO
    mcp_server: DEBUG