server:
  port: 8084

spring:
  application:
    name: fs-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://mcp-lab-otel-collector:4318/v1/traces}

logging:
  level:
    root: INFO
    fs_server: DEBUG
